### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by archcra** [NeoCat/sl_on_touchbar#1]
No effect, no error, just make some area of the touchbar blank.

before execute ./sl
<img width="1085" alt="before" src="https://user-images.githubusercontent.com/6466550/32879031-509f3426-cae3-11e7-9fec-198a075cca13.png">

and after:
<img width="1085" alt="after" src="https://user-images.githubusercontent.com/6466550/32879035-55cb9426-cae3-11e7-81aa-7a36d011d1da.png">

If this app works, I am sure I will like it.

**Comment by NeoCat** [comment]
I have rebuilt the app for macOS 10.12+ and now it should work.
